### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tinwinaung** [AndrejGajdos/link-preview-generator#1]
I am using it in Windows 10 nodejs and got the following error while CPU is heavily busy

(node:5176) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:5176) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:5176) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:5176) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
(node:5176) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __puppeteer_evaluation_script__:14:44

**Comment by AndrejGajdos** [comment]
@tinwinaung What url are you trying to parse? Do you see this error message in other OS?

**Comment by AndrejGajdos** [comment]
Closed due to inactivity.
