### ISSUE TITLE
amazon images are coming with review and rating

### ISSUE THREAD

**Issue by helloworldkr** [AndrejGajdos/link-preview-generator#10]
I am trying to generating an amazon product URL preview with the image.
Your library has been very helpful to get me the image of the product but review and rating not required in my and they are appearing. 
Is there any workaround for that.
![image](https://user-images.githubusercontent.com/9402190/91687195-c6ae3880-eb7c-11ea-89c2-f611c9728fd2.png)

I just want the product image only.

**Comment by AndrejGajdos** [comment]
Just use [object destructuring](https://exploringjs.com/impatient-js/ch_destructuring.html#object-destructuring).
