### ISSUE TITLE
Evaluation failed: ReferenceError: uri is not defined

### ISSUE THREAD

**Issue by arminfro** [AndrejGajdos/link-preview-generator#15]
Thanks for your library. It works well, just this link: [https://yarnpkg.com](https://yarnpkg.com) doesn't.

Here is some of the stack trace:
`Error: Evaluation failed: ReferenceError: uri is not defined\n    at <anonymous>:48:37\n    at Array.forEach (<anonymous>)\n    at <anonymous>:46:14\n    at ExecutionContext._evaluateInternal (./node_modules/puppeteer/lib/ExecutionContext.js:122:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async ExecutionContext.evaluate (./node_modules/puppeteer/lib/ExecutionContext.js:48:12)\n    at async getImg (./node_modules/link-preview-generator/index.js:18:15)\n    at async module.exports (./node_modules/link-preview-generator/index.js:176:13)`

I'm not sure if it's `link-preview-generator` or `puppeteer` which needs a fix. The error also appears in the provided heroku demo

**Comment by AndrejGajdos** [comment]
@arminfro fixed [here](https://github.com/AndrejGajdos/link-preview-generator/commit/07094cc796e80a98be20d11e9c6603b64e0418cc)
