### ISSUE TITLE
Undefined variable src

### ISSUE THREAD

**Issue by tgdn** [AndrejGajdos/link-preview-generator#19]
`src` is never defined in https://github.com/AndrejGajdos/link-preview-generator/blob/75cded00a32ced8e4cebad4ea76ed622deaf47af/index.js#L69

`paragraphs` isn't defined either at https://github.com/AndrejGajdos/link-preview-generator/blob/75cded00a32ced8e4cebad4ea76ed622deaf47af/index.js#L127

**Comment by AndrejGajdos** [comment]
Thank you. It should be fixed now.
