### ISSUE TITLE
Deploy to Amazon AWS

### ISSUE THREAD

**Issue by inPhilly** [AndrejGajdos/link-preview-generator#2]
This is all very new to me. I saw you deployed the demo to Heroku, but it seems that to use this as an API for a mobile app in production, it would have to be deployed to someplace like AWS. I looked at the documentation for npm and I couldn't find out how this would be used to create a business-use API. Can you direct me in the right direction?

**Comment by AndrejGajdos** [comment]
Hi there, I already answered you in the [blog post](https://andrejgajdos.com/how-to-create-a-link-preview/). I hope it helps.
