### ISSUE TITLE
Is lattest code working?

### ISSUE THREAD

**Issue by zigmok** [AndrejGajdos/link-preview-generator#20]
Demos are not working. 

After running: 
> const linkPreviewGenerator = require("link-preview-generator");
> const previewData = linkPreviewGenerator("https://www.youtube.com/watch?v=8mqqY2Ji7_g");
> console.log(previewData);
Promise { <pending> }

This hangs out here:

> (node:12888) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded at C:\lpg\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatch er.js:106:111

Any ideas of how to make it work?

**Comment by AndrejGajdos** [comment]
@zigmok I don't know why the project wasn't running on Heroku. There were errors in log file:

`at=error code=H10 desc="App crashed" method=GET path="/" host=link-preview-generator.herokuapp.com request_id=9756495d-e5b8-4381-978c-99206ad23f6b fwd="61.166.192.69" dyno= connect= service= status=503 bytes= protocol=http`

I restarted dynos and it should work again. Thank you and let me know if it doesn't work for you.
