### ISSUE TITLE
Any way to import and use this library directly without the yarn/npm project setup?

### ISSUE THREAD

**Issue by ashishb** [AndrejGajdos/link-preview-generator#23]

**Comment by AndrejGajdos** [comment]
Where/what type of project you want to import this library?

**Comment by ashishb** [comment]
A stand-alone web page. See
https://reading.ashishb.net/v3/r?url=https://ferd.ca/complexity-has-to-live-somewhere.html#para-19
as an example.

**Comment by AndrejGajdos** [comment]
This is a node.js library, it's not possible to run it in web page.
