### ISSUE TITLE
<h2> tags not used

### ISSUE THREAD

**Issue by GPrev** [AndrejGajdos/link-preview-generator#27]
This is a minor bug but h2 tags are never used as a title.
See the code below from index.js, where both parts parse the h1 header :
```js
const h1 = document.querySelector("h1").innerHTML;
if (h1 != null && h1.length > 0) {
  return h1;
}
const h2 = document.querySelector("h1").innerHTML;
if (h2 != null && h2.length > 0) {
  return h2;
}
```
I'm not sure how useful it is to get h2 tags, but I thought it couldn't hurt to fix it.

**Comment by AndrejGajdos** [comment]
@GPrev I am pretty sure I came across websites without `h1` and instead `h2` was used as the main header.
