### ISSUE TITLE
Some URLs result in TypeError: Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by peacechen** [AndrejGajdos/link-preview-generator#3]
Thanks for sharing this handy preview generator.  It works on most links, but a few are failing:

https://www.bloomberg.com/news/articles/2020-03-27/trump-threatens-to-force-gm-to-move-faster-on-ventilators

> Error: Evaluation failed: TypeError: Cannot read property 'src' of undefined
>     at __puppeteer_evaluation_script__:50:22
>     at ExecutionContext._evaluateInternal ((...)\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   -- ASYNC --
>     at ExecutionContext.<anonymous> ((...)\node_modules\puppeteer\lib\helper.js:111:15)
>     at DOMWorld.evaluate ((...)\node_modules\puppeteer\lib\DOMWorld.js:112:20)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   -- ASYNC --
>     at Frame.<anonymous> ((...)\node_modules\puppeteer\lib\helper.js:111:15)
>     at Page.evaluate ((...)\node_modules\puppeteer\lib\Page.js:860:43)
>     at Page.<anonymous> ((...)\node_modules\puppeteer\lib\helper.js:112:23)
>     at getImg ((...)\node_modules\link-preview-generator\index.js:18:26)
>     at module.exports ((...)\node_modules\link-preview-generator\index.js:174:19)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>

**Comment by AndrejGajdos** [comment]
Its fixed and I released new npm version.

Btw good luck with scraping Bloomberg. They don't like scraping their website and use some antirobots mechanisms. Pls let me know how it goes.
