### ISSUE TITLE
https://link-preview-generator.herokuapp.com/ down

### ISSUE THREAD

**Issue by alxnbl** [AndrejGajdos/link-preview-generator#41]
Hey,

First of all, thank you for this great library. 
I use your demo website to generate preview for my website and it seams to be down since a couple of days. The website is not really par of this repository but it was a way to notice you.

Alex

**Comment by AndrejGajdos** [comment]
Thanks, I know about this. Unfortunately Heroku ended their free plan some time ago.

**Comment by alxnbl** [comment]
Ok shame. Thank you for the answer.
