### ISSUE TITLE
Problem with WebSocketTransport

### ISSUE THREAD

**Issue by imprakashraghu** [AndrejGajdos/link-preview-generator#6]
```
This dependency was not found:
* ws in ./node_modules/puppeteer/lib/WebSocketTransport.js
To install it, you can run: npm install --save ws
```

used in Vuejs project
even after installing ws , still same error!

**Comment by AndrejGajdos** [comment]
This is a Node.js library, you cannot use it in a Vue project.

**Comment by bipindubey-technoark** [comment]
I am also getting same problem 

```
index.js:1 ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in 'E:\linkedinvestor\node_modules\puppeteer\lib'
```

I am using Reactjs
Cant i use it in reactjs??
@AndrejGajdos

**Comment by AndrejGajdos** [comment]
@bipindubey-technoark this is node.js library, which is not possible to use on front-end.
