### ISSUE TITLE
error while loading shared libraries libx11-xcb.so.1

### ISSUE THREAD

**Issue by MattB543** [AndrejGajdos/link-preview-generator#7]
Hi there, firstly, I love this link preview generator.  Your blog post spells it out very cleanly.

Anyway, it works beautifully locally but then when we tried to launch it live (in our docker) it errors out.

We don't get the error locally, do we really have to add a bunch of packages like this article suggests?

https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3

![image (24)](https://user-images.githubusercontent.com/45475210/87606212-67798f00-c6c8-11ea-94dc-97035d40629b.png)

**Comment by AndrejGajdos** [comment]
You need to find out how to run Puppeteer in Docker. Maybe #4 can help you. I needed to add some buildpacks in Heroku and I think you would need to add some packages in Docker.
